#UNIVERSIDAD NACIONAL AUTONOMA DE MEXICO
#FACULTAD DE ESTUDIOS SUPERIORES ARAGON
#INGENIERIA EN COMPUTACION
#CRUZ JUAREZ EZEQUIEL AMADO
#SISTEMAS EXPERTOS
#GUI
from Antropometria import ventana_inicial
ventana_inicial()
